---
name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 5 * * 0"
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y shellcheck
          shellcheck --version

      - name: Lint
        run: |
          grep -rl '^#!/.*sh' * | xargs -n1 shellcheck -e SC2059

  yamllint:
    name: yamllint

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Run yamllint
        run: |
          python3 --version
          pip3 install --user yamllint
          yamllint --version
          yamllint --list-files .
          yamllint .
