name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 0"
  workflow_dispatch:

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y shellcheck
        shellcheck --version

    - name: Lint
      run: |
        grep -rl '^#!/.*sh' * | xargs -n1 shellcheck
